import userRoutes from "../routes/userRoutes.js";
import busniessRoutes from "../routes/busniessRoutes.js";
import serviceRoutes from "../routes/serviceRoutes.js";
import chatRoutes from "../routes/chatRoutes.js";
import ratingRoutes from "../routes/ratingRoutes.js";
import notificationRoutes from "../routes/notifcaitonRoutes.js";
import requestRoutes from "../routes/requestRoutes.js";
import paymentRoutes from "../routes/paymentRoutes.js";
import categoryRoutes from "../routes/categoryRoutes.js";
import assignJobRoutes from "../routes/assignJobRoutes.js";
import jobPromotionRoutes from "../routes/jobPromotion.js";
import express from "express";
import authMiddleware from "../middleware/authMiddleware.js";
const router = express.Router();
router.use("/user", userRoutes);
router.use("/busniess", busniessRoutes);
router.use("/service", serviceRoutes);
router.use("/chat", chatRoutes);
router.use("/category", categoryRoutes);
router.use("/rating", ratingRoutes);
router.use("/notification",notificationRoutes);
router.use("/request", requestRoutes);
router.use("/payment",  paymentRoutes);
router.use("/assignJobs",  assignJobRoutes);
router.use("/promotion", jobPromotionRoutes);
export default router;
