import userRoutes from '../routes/userRoutes.js';
import busniessRoutes from '../routes/busniessRoutes.js';
import serviceRoutes from '../routes/serviceRoutes.js';
import chatRoutes from '../routes/chatRoutes.js';
import ratingRoutes from '../routes/ratingRoutes.js';
import notificationRoutes from '../routes/notifcaitonRoutes.js';
import requestRoutes from '../routes/requestRoutes.js';
import paymentRoutes from '../routes/paymentRoutes.js';
import categoryRoutes from '../routes/categoryRoutes.js';
import assignJobRoutes from '../routes/assignJobRoutes.js';
import express from 'express';
import authMiddleware from '../middleware/authMiddleware.js';
const router = express.Router();
router.use("/user", userRoutes);
router.use("/busniess", busniessRoutes);
router.use("/service", serviceRoutes);
router.use("/chat", chatRoutes);
router.use("/category", categoryRoutes);
router.use("/rating", authMiddleware, ratingRoutes);
router.use("/notification", authMiddleware, notificationRoutes);
router.use("/request", authMiddleware, requestRoutes);
router.use("/payment", authMiddleware, paymentRoutes);
router.use("/assignJobs", authMiddleware, assignJobRoutes);
export default router;